"""
State Definitions for the Researcher Sub-graph.

This module defines the local state used by each researcher worker agent
during parallel execution within the research phase.
"""

from typing import Annotated, List
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class ResearcherState(TypedDict):
    """
    Represents the isolated state for an individual researcher agent.

    Each researcher operates independently on a single sub-topic as part of
    a parallel (fan-out) execution strategy. This state ensures that each worker
    maintains its own context while still contributing results back to the
    global state (fan-in).

    Attributes:
        current_topic (str):
            The specific sub-topic assigned to this researcher.
            This defines the scope of the agent's work.

        messages (List[BaseMessage]):
            The local conversation history for this researcher agent.
            This includes prompts, intermediate reasoning steps, and responses.
            The `add_messages` annotation ensures new messages are appended
            automatically during execution.

        iteration_count (int):
            Tracks the number of iterations or reasoning steps performed by
            the researcher. This can be used to limit loops, control depth,
            or enforce stopping conditions.

        aggregated_notes (List[str]):
            A list of notes, findings, or extracted insights generated by
            the researcher.

            This field is intentionally aligned with the same field in the
            global state to support fan-in aggregation, where results from
            multiple parallel researchers are merged into a single collection.
    """
    current_topic: str
    messages: Annotated[List[BaseMessage], add_messages]
    iteration_count: int
    
    aggregated_notes: List[str]